trigger:
  # Pipeline will run for any update pushed to the below listed branches
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#ci-triggers
  branches:
    include:
      - dev
      - main
  paths:
    exclude:
      - ios
      - pipelines/build-ios.yml
      - .editorconfig
      - .gitattributes
      - .gitignore
      - .eslintrc.json
      - README.md

# Pipeline will run for PRs targeting the below listed branches
# https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#pr-triggers
pr:
  branches:
    include:
      - dev
      - hotfix/*
      - release/*
  paths:
    exclude:
      - ios
      - pipelines/build-ios.yml
      - .editorconfig
      - .gitattributes
      - .gitignore
      - .eslintrc.json
      - README.md


jobs:
  - job: Phase_1
    displayName: Build Android
    timeoutInMinutes: 45
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: ubuntu-latest
    steps:
      # Checkout
      - checkout: self

      # NodeTool@16
      - task: NodeTool@0
        displayName: "Use Node 16.x"
        inputs:
          versionSpec: '16.x'
      
      - script: |
          yarn install
        displayName: "Install modules"

      # Print Java Version
      - task: CmdLine@2
        displayName: Print Java version
        inputs:
          script: java -version